yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('follow/', views.follow_index, name='follow_index'),
    path('new/', views.new_post, name='new_post'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path('<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('<str:username>/<int:post_id>/delete/',
         views.post_delete,
         name='delete'
         ),
    path('<username>/<int:post_id>/comment',
         views.add_comment, name='add_comment'),
    path('404', views.page_not_found, name='404_error'),
    path('500', views.server_error, name='500_error'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="posts")
    group = models.ForeignKey("Group",
                              on_delete=models.SET_NULL,
                              blank=True, null=True,
                              related_name="groups")
    image = models.ImageField(upload_to="posts/", blank=True, null=True)

    class Meta:
        ordering = ["-pub_date"]

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey("Post",
                             on_delete=models.CASCADE,
                             blank=True, null=True,
                             related_name="comments")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField("date published", auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="follower")
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="following")

yatube/posts/forms.py
from django import forms
from django.forms.widgets import Textarea

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': ('Текст сообщения'),
            'group': ('Группа'),
            'image': ('Изображение')
        }
        help_texts = {
            'text': ('Тут можно оставить послание для потомков'),
            'group': ('Кошечки, собачки... выбирай, что нравится'),
            'image': ('Добавить изображение')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {'text': Textarea}
        labels = {'text': 'Текст комментария'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    main = True
    return render(
        request,
        'index.html',
        {'page': page, 'index': main}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'group.html',
        {'page': page, 'group': group}
    )


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    count_posts = post_list.count()
    count_following = author.follower.count()
    count_followers = author.following.count()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    user = request.user
    if user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
        return render(
            request,
            'profile.html',
            {'page': page, 'author': author,
             'count_posts': count_posts, 'username': username,
             'following': following, 'count_following': count_following,
             'count_followers': count_followers}
        )
    return render(
        request,
        'profile.html',
        {'page': page, 'author': author,
         'count_posts': count_posts, 'username': username,
         'count_following': count_following,
         'count_followers': count_followers}
    )


def post_view(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    author = post.author
    count_posts = author.posts.all().count()
    count_following = author.follower.count()
    count_followers = author.following.count()
    comments = Comment.objects.filter(post=post)
    form = CommentForm()
    return render(
        request,
        'post.html',
        {'post': post, 'author': author, 'count_posts': count_posts,
         'post_id': post_id, 'username': username,
         'comments': comments, 'form': form,
         'count_following': count_following,
         'count_followers': count_followers}
    )


@login_required
def new_post(request):
    header = 'Добавить запись'
    card_header = 'Новая запись'
    action = 'Добавить'
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('index')
    return render(
        request,
        'new.html',
        {'form': form, 'header': header,
         'action': action, 'card_header': card_header}
    )


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    user = request.user
    if not author.username == user.username:
        return redirect('post', username=username, post_id=post_id)
    header = 'Редактировать запись'
    card_header = 'Редактируемая запись'
    action = 'Сохранить'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        mid_post = form.save(commit=False)
        mid_post.author = request.user
        mid_post.save()
        return redirect('post', username=username, post_id=post_id)
    return render(
        request,
        'new.html',
        {'post': post, 'form': form, 'header': header, 'action': action,
         'post_id': post_id, 'username': username,
         'card_header': card_header}
    )


def page_not_found(request, exception):
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)


@login_required
def add_comment(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    form = CommentForm(request.POST or None,)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect(reverse('post', args=[username, post_id]))
    return redirect(reverse('post', args=[username, post_id]))


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    follow = True
    return render(
        request,
        'follow.html',
        {'page': page, 'follow': follow}
    )


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if not Follow.objects.filter(
        user=user,
        author=author
    ).exists() and user != author:
        Follow.objects.create(user=user, author=author)
    return redirect('profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    follow = Follow.objects.filter(
        user=user,
        author=author
    )
    if follow.exists() and user != author:
        follow.delete()
    return redirect('profile', username)


@login_required
def post_delete(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    user = request.user
    if not author.username == user.username:
        return redirect('post', username=username, post_id=post_id)
    post.delete()
    return redirect('index')

yatube/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            Join the Darkside! We have some cookies!
        {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            <h1>
                {% block header %}
                    Join the Darkside! We have some cookies!
                {% endblock %}
            </h1>
                {% block content %}

                {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

yatube/templates/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <form method="post" action="{% url 'add_comment' username post_id %}">
      {% csrf_token %}
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <div class="form-group">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </div>
    </form>
  </div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
  <div class="media card mb-4">
    <div class="media-body card-body">
      <h5 class="mt-0">
        <a
          href="{% url 'profile' item.author.username %}"
          name="comment_{{ item.id }}"
        >@{{ item.author.username }}</a>
      </h5>
      <p>{{ item.text|linebreaksbr }}</p>
      <small class="text-muted">{{ item.created|date:"d M Y" }}</small>
    </div>
  </div>
{% endfor %}

yatube/templates/follow.html
{% extends "base.html" %}
{% block title %}Join the Darkside! We have some cookies{% endblock %}
{% block header %}Избранные авторы{% endblock %}
{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}

    {% for post in page %}
      {% include "post_item.html" with post=post %}
    {% endfor %}

    {% include "paginator.html" with items=page paginator=paginator %}

  </div>
{% endblock %}

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <a class="btn btn-sm btn-dark" href="{% url 'about:author' %}" role="button">
        Об авторе
    </a>
    <a class="btn btn-sm btn-dark" href="{% url 'about:tech' %}" role="button">
        О технологии
    </a>
    <p class="m-0 text-dark text-center ">Second Galactic Empire <span style="color:black">Darth</span><span style="color:red">Cookies</span> © {% now "Y" %}, все права защищены.</p>
    
</footer>

yatube/templates/group.html
{% extends "base.html" %}

{% block title %}
    Записи сообщества {{ group.title }} | Yatube
{% endblock %}

{% block header %}
    {{ group.title }} 
{% endblock %}

{% block content %}
    <p>{{ group.description }}</p>
    
    {% for post in page %}
        {% include 'post_item.html' with post=post %}
    {% endfor %}

    {% include "paginator.html" with items=page paginator=paginator%}
    
{% endblock %} 

yatube/templates/index.html
{% extends "base.html" %}
{% block title %}Join the Darkside! We have some cookies{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
<div class="container">

  {% include "menu.html" with index=True %}
  {% load cache %}
  {% cache 20 index_page %}

  {% for post in page %}
    {% include "post_item.html" with post=post %}
  {% endfor %}
  {% endcache %}
  {% include "paginator.html" with items=page paginator=paginator %}

</div>
{% endblock %}

yatube/templates/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index and not follow %}active{% endif %}" href="{% url 'index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background: linear-gradient(to left, #ff0000 0%, #660033 100%);">
    <a class="navbar-brand" href="{%url 'index' %}"><span style="color:black">Darth</span><span style="color:red">Cookies</span></a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a href="{%url 'profile' user.username %}" role="button">
            @{{ user.username }}.
          </a>
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

yatube/templates/new.html
{% extends "base.html" %}

{% block header %} 
{{ header }}
{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Новая запись</div>
            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                    <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                    <div class="col-md-6">
                                        {{ field|addclass:"form-control" }} 
                                        {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                        {% endif %}
                                    </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                {{ action }}
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

yatube/templates/paginator.html
{% if page.has_other_pages %}
    <nav>
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Предыдущая</span>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}
                            <span class="sr-only">(текущая)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Следующая &raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

yatube/templates/post.html
{% extends "base.html" %}


{% block content %}
<main role="main" class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">  
          <div class="card-body">
            <div class="h2">
              {{ author.get_full_name }}
            </div>
            <div class="h3 text-muted">
              {{ username }}
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h6 text-muted">
                Подписчиков: {{ count_followers }} <br />
                Подписан: {{ count_following }}
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Записей: {{ count_posts }}
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-9">
          {% include 'post_item.html' with post=post %}
          {% include 'comments.html' %}
      </div>
      <hr>
    </div>
</main>

{% endblock %} 

yatube/templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" height="339">
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
      <a class="card-link muted" href="{% url 'group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
          <a class="btn btn-sm btn-warning" href="{% url 'edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          <a class="btn btn-sm btn-danger" href="{% url 'delete' post.author.username post.id %}" role="button">
            Удалить
          </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>

yatube/templates/profile.html
{% extends "base.html" %}


{% block content %}
<main role="main" class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">  
          <div class="card-body">
            <div class="h2">
              {{ author.get_full_name }}
            </div>
            <div class="h3 text-muted">
              {{ username }}
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h6 text-muted">
                Подписчиков: {{ count_followers }} <br />
                Подписан: {{ count_following }}
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Записей: {{ count_posts }}
              </div>
            </li>
            <li class="list-group-item">
              {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'profile_unfollow' username %}" role="button">
                  Отписаться
                </a>
              {% else %}
                <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'profile_follow' username %}" role="button">
                  Подписаться
                </a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-9">
          {% for post in page %}
            {% include 'post_item.html' with post=post %}  
          {% if not forloop.last %}{% endif %}
          {% endfor %}    
          {% include "paginator.html" with items=page paginator=paginator%}
      </div>
    </div>  
</main>

{% endblock %} 